version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing Terraform..."
      - wget -q https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip -q terraform_${TF_VERSION}_linux_amd64.zip
      - chmod +x terraform
      - mv terraform /usr/local/bin/
      - terraform version
  build:
    commands:
      - echo "Deploying infrastructure..."
      - cd terraform
      - terraform init
      - |
        # Create terraform.tfvars from environment variables
        cat > terraform.tfvars <<EOF
        admin_emails = ["${ADMIN_EMAIL}"]
        google_client_id = "${GOOGLE_CLIENT_ID}"
        google_client_secret = "${GOOGLE_CLIENT_SECRET}"
        allowed_origins = [$(echo "$ALLOWED_ORIGINS" | awk -F',' '{for(i=1;i<=NF;i++) printf "\"%s\"%s", $i, (i<NF?",":"")}')]
        EOF
      - terraform plan -out=tfplan
      - terraform apply -auto-approve tfplan
  post_build:
    commands:
      - echo "Deployment completed"
      - terraform output


